name: polypick_enterprise
description: PolyPick Engineers - World's Most Advance AI Dialer - Raju Singh Original
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_tts: ^4.0.2
  speech_to_text: ^6.5.1
  permission_handler: ^11.3.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.2
  record: ^5.0.4
  telephony: ^0.2.0
  contacts_service: ^0.6.3
  intl: ^0.19.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
